# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147woLot8yAah0Z-6lqqwCtnn3wgc8yMW
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from io import BytesIO
import os
import time
import qrcode

app = FastAPI()

# Sirve /static/driver.html, /static/tracking.html, /static/logo.png, etc.
app.mount("/static", StaticFiles(directory="static"), name="static")

# Memoria simple por token
services = {}  # token -> {lat, lon, ts, finished}

class UpdateBody(BaseModel):
    lat: float
    lon: float

def _ensure_service(token: str):
    if token not in services:
        services[token] = {"lat": -34.6083, "lon": -58.3712, "ts": None, "finished": False}

def _render_template(filename: str, **kwargs) -> str:
    path = os.path.join("static", filename)
    with open(path, "r", encoding="utf-8") as f:
        html = f.read()
    for k, v in kwargs.items():
        html = html.replace(f"%%{k}%%", str(v))
    return html

@app.get("/", response_class=HTMLResponse)
def home():
    return HTMLResponse("<h3>OK</h3><p>Usá /driver/{token} o /seguir/{token} o /qr/{token}.png</p>")

@app.get("/driver/{token}", response_class=HTMLResponse)
def driver_page(token: str):
    _ensure_service(token)
    return HTMLResponse(_render_template("driver.html", TOKEN=token))

@app.get("/seguir/{token}", response_class=HTMLResponse)
def tracking_page(token: str):
    _ensure_service(token)
    titulo = token.replace("-", " ")
    return HTMLResponse(_render_template("tracking.html", TOKEN=token, TITULO=titulo))

@app.post("/update/{token}")
def update_location(token: str, body: UpdateBody):
    _ensure_service(token)
    if services[token]["finished"]:
        raise HTTPException(status_code=410, detail="Servicio finalizado")

    services[token]["lat"] = body.lat
    services[token]["lon"] = body.lon
    services[token]["ts"] = int(time.time())
    return {"ok": True}

@app.get("/last/{token}")
def last_location(token: str):
    if token not in services:
        raise HTTPException(status_code=404, detail="Servicio inexistente")
    if services[token]["finished"]:
        raise HTTPException(status_code=410, detail="Servicio finalizado")
    if services[token]["ts"] is None:
        raise HTTPException(status_code=404, detail="Sin ubicación todavía")

    return {
        "lat": services[token]["lat"],
        "lon": services[token]["lon"],
        "ts": services[token]["ts"],
    }

@app.post("/finish/{token}")
def finish_service(token: str):
    _ensure_service(token)
    services[token]["finished"] = True
    return {"ok": True}

@app.get("/qr/{token}.png")
def qr_png(token: str):
    # QR apunta al seguimiento público en el mismo dominio
    base = os.getenv("PUBLIC_BASE_URL", "").strip().rstrip("/")
    if not base:
        # fallback local si no está configurado
        base = "http://127.0.0.1:8000"

    full = f"{base}/seguir/{token}"

    qr = qrcode.QRCode(border=2, box_size=10)
    qr.add_data(full)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    buf = BytesIO()
    img.save(buf, format="PNG")
    return Response(content=buf.getvalue(), media_type="image/png")

